size = 224 64
length = 3.500000 0.50000
velocity = 0.1000000 0.000000
pressure = 0.000000
geometry = free
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
I                                                                                                                                                                                                                              O
-------------------------KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK#######################################################################################################################################
